### ISSUE TITLE
Compiling flags for C  tools.

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#101]

**Comment by keeferrourke** [comment]
Main issue: #85.

**Comment by ian-james** [comment]
Might have to cheap out on this and offer a small subset of libraries like math. Will take a larger look soon.

**Comment by keeferrourke** [comment]
A better implementation could always be rolled out in the future, as long as we are offering a minimal working subset of features?

**Comment by keeferrourke** [comment]
I have created a branch 'compiler-flags' which implements a basic version of the feature requested in issue #85. Commit https://github.com/ian-james/IFS/commit/fcfbee856c5659f33d53a0d55c29072dfdc0abc0 patches the IFS to allow text-inputs, and safeguards against empty text inputs -- it is up to the Python tools to validate this input.

programmingParser.py has been patched to handle malformed compilation flags.

Testing will be needed before this is merged to master.

**Comment by ian-james** [comment]
This has been resolved and integraded.
