### ISSUE TITLE
Extend about page to include how to use and goals of research. Maybe a welcome page.

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#103]

**Comment by keeferrourke** [comment]
I just pushed a minor update to the about page re: this issue. I'm hoping that it provides a user-friendly summary of what are trying to do with this website. Feel free to edit as required.

I'm not sure what would be expected for a welcome page. Would this be on the /register and /login routes? An extension of the /setup route?

**Comment by ian-james** [comment]
Welcome page probably not necessary anymore.

I was looking for something in the range of 'tutorial' or video feature demo so that students know about the features.

**Comment by keeferrourke** [comment]
I could look into making a screen cast that showcases the general workflow of the IFS?

**Comment by keeferrourke** [comment]
I'm going to mark this issue as closed since commit 45c4fcf88f032e62d0a4835f8e974268ecfec564 seems to have this covered. If we want to have additional tutorial-type resources for how to use the IFS, we can continue discussion here or open a new issue at your discretion.
