### ISSUE TITLE
Make experiment opt-in/out require email confirmation?

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#105]

**Comment by keeferrourke** [comment]
@ian-james could you please provide a description for this issue?

**Comment by ian-james** [comment]
Weird Description didn't get uploaded.

Basically, I was wondering what the scope of extending the forgotten password mailer into a system that also confirms a students opt-in and opt-out  status by. Right now as we have the power to change students registration options which although in practice wouldn't come into play but still has the potential for unethical usage. If we also send an email on status changes of experiment registration to yourselves and the student it would create a consistent participation acknowledgement. This is just an idea.

**Comment by keeferrourke** [comment]
Oh good idea! I need to clean up the code in the verify module, but I think it should be easy to extend the link-verification/email to apply to other parts of the application. I will look into this.

**Comment by keeferrourke** [comment]
TODO:
- [x] Modularize email/link generation
- [ ] Implement email confirmations for experiment opt-in/opt-out

**Comment by keeferrourke** [comment]
See commit https://github.com/ian-james/IFS/commit/be93d62a408bacfcfe8628be45569cccc8804a92

**Comment by keeferrourke** [comment]
Reassigning the reset of this issue to you @ian-james, I am not sure how you want to handle opt-in/opt-out verification, but the Verify module provides a simple interface for doing so via email.

**Comment by ian-james** [comment]
Closing this issue since the student has the ability to opt-in/out at any point in IFS.
Email confirmation is likely overkill
