### ISSUE TITLE
[Critical Functionality] Skills sometimes cannot be added

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#108]
### Description
There is a problem on the /skills route where updating values under 'Course Skills' does not update 'Student Skills. I have attached a [screen recording](https://krourke.org/files/ifs-skills-bug.webm) of this issue and screen shots of the Admin pages to show what is currently in my database.

![image](https://user-images.githubusercontent.com/6888381/29997867-75ccb066-8fec-11e7-93b1-56eaccaa987f.png)
![image](https://user-images.githubusercontent.com/6888381/29997869-8d855082-8fec-11e7-80e5-38af4841b22c.png)
![image](https://user-images.githubusercontent.com/6888381/29997872-9bd2a20c-8fec-11e7-8a3a-20c18b70859d.png)
![image](https://user-images.githubusercontent.com/6888381/29997874-a7bc5af4-8fec-11e7-8f54-a96a2ea7c3a4.png)
![image](https://user-images.githubusercontent.com/6888381/29997877-b1714c76-8fec-11e7-9ec1-d7f8fadbae5f.png)

### Expected behaviour

Linked List skills should have been added to my Student Skills.

### Actual behaviour
Nothing happened.

### Steps to reproduce

 1. Setup databases similar to mine, as shown in screenshots.
 2. Make student select proficiency in one skill.
 3. Go back to student skill page and attempt to increase proficiency in a new class skill.
 4. Skill fails to be added to student skills.

#### IFS Version

v0.0.2

**Comment by ian-james** [comment]
This bug has been introduced and reintroduced lately as the dashboard ui has been changing it breaks the jquery. Although, since the last couple commits there seems to be bigger issues with the dashboard.

**Comment by keeferrourke** [comment]
@ian-james sorry about that; I wasn't aware. I didn't think that revising the dashboard layouts and styling via classes would could have such an effect.

**Comment by ian-james** [comment]
No worries, its a good indication that the code should be changed too.
If changing the UI breaks the code it's usually can be done better. Tried to improve to code.

**Comment by ian-james** [comment]
Should be resolved fixed jquery. Reopen if not true.
