### ISSUE TITLE
Tooltips on skill bars is no longer showing

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#111]

**Comment by ian-james** [comment]
On the dashboard, a horizontal line appears above the skill meter but does not show the number.

**Comment by keeferrourke** [comment]
Not totally sure if this is the problem (I have not looked into it), but UIKit tooltips can only show on HTML entity which accept the `title` attribute. In cases where I needed a tooltip but couldn't use such an entity, I made fake tooltips using popovers (as you might see in Preferences, etc).

I will look into this tomorrow.

**Comment by keeferrourke** [comment]
I am not sure what is meant by
> On the dashboard, a horizontal line appears above the skill meter but does not show the number.

But as of commit c295e04 skills are now tooltipped with descriptions.

![screenshot from 2017-09-04 11-46-44](https://user-images.githubusercontent.com/6888381/30033023-c3575798-9166-11e7-9a3a-b4ef462778f7.png)

**Comment by ian-james** [comment]
Yes, I do like the description on skill page that looks great.

On the dashboard page though when you hover over the skill meter, it used to show the numeric value as a tooltip. My experience is that no tooltip shows up but a horizontal line above the skill.


![skillmeterhorizontallinebug](https://user-images.githubusercontent.com/4433774/30034612-7498193a-9170-11e7-9301-cc826c9936b0.png)

**Comment by ian-james** [comment]
Testing all functionality has a line above it on right screen.

**Comment by keeferrourke** [comment]
Oh I see; yeah this is due to the fact that progress bars are not allowed to take 'title' attributes, which UIKit uses to populate tooltips. I'll find a work around and push it as soon as I can.

**Comment by ian-james** [comment]
Closing this not that valuable.
