### ISSUE TITLE
cppcheck generates error feedback on all tool feedback pages when used

### ISSUE THREAD

**Issue by johndanielharmer** [ian-james/IFS#120]
### Description
cppcheck generates a tool warning on every tool feedback page when expected .h files are not present in a submission.

### Actual behaviour
When uploading files or directories which have .h dependencies which are not included in the directory, cppcheck generates a correct error. However, it shows this for every tool feedback page, including when selecting specific tools like clang or gcc. It should only be showing in the "all" and "cppcheck" pages.

Example: 
cppcheck | information | Cppcheck cannot find all the include files (use --check-config for details) | "" | "" | ""

### Steps to reproduce
1. Navigate to the programming tool upload page.
2. Enable the cpp tool and any number of other tools. Pick at least 1 other tool. The options don't seem to be relevant to this bug.
3. Upload a folder or file which needs a .h file to compile, but omit the .h file.
4. Click "View Feeback"
5. Click on the "Click to expand" message at the top. The error should be visible along with all other tools.
6. Change the tool in the dropdown bar at the top of the page to any non-cpp tool.
7. Repeat step 5. cppcheck will generate a warning despite not being selected as the tool displaying feedback.

#### IFS Version
v0.0.3 dev

#### Browser
Please tick the affected browsers.

 - [x] Chrome/Chromium-based
 - [ ] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

**Comment by GrantDouglas** [comment]
Have tested this and it seems to be fine for now. Closing
