### ISSUE TITLE
Tests->Student Course Information

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#131]
This is the student side of course information.

Includes enrolling and being displayed in preferences and dashboard.
Would include correctly viewing their classes stats in Student /social models.

**Comment by ryoung2512** [comment]
Does this feature already exist? I am unable to find any of this.

**Comment by ian-james** [comment]
When a student first logins or goes to /courses they see their course information.
Preferences is just in the preferences
For  social models mostly just accessing the page and changing any options that could be tested.

These would all have DB tests as well

**Comment by ryoung2512** [comment]
I more meant, does the actual feature to enroll in a course exist. As in, does it exist other than when you are first logging in.

**Comment by ian-james** [comment]
Right now you can return to /course or /course route,I believe through
preferences or at least in some version in IFS that was true.
