### ISSUE TITLE
IFS -> Submissions of Large files occassional drops a file.

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#143]
Identified by John

Occasionally, IFS will drop a file if a number of files are submitted and 1+ are large. 
Tended to be the large file that was dropped.

Solution: The issue appeared to stem from the asynchronous creation of the users/submission folder which was being erased and recreated between file uploads. The folder creation needs to happen once at submission and then upload files.

**Comment by ryoung2512** [comment]
John and I looked into it. We were able to fix the problem of having the files deleted, by using ensureDir to ensure the directory exists if not make it. As well as timestamps for the folder directory. With that being said another bug has emerged which is that it will create a second folder a millisecond later sometimes. This needs to be addressed but is difficult cuz we have to sift through a bunch of files.

We will probably wait until you are back to get your input on how some of it works.

**Comment by ian-james** [comment]
Something like the code you're talking about previously exists in GitHub.
Basically, you want to round or chop the timestamp based on a reasonable
assumption. As students, aren't submitting every second but maybe every 5
seconds. Thus, really a timestamp has to a minimum chop the ms and possibly
even the 1st digit of seconds. There are other ways to do this of course
just saying that exists if you look back in history.

Realistically, I'm going to push for saving all submission again in an
ethics document soon. So this only requires minor adjustments to the saving
structure of submissions.

In addition, we need to perhaps move the clearing of the directory or
creating of a new directory if saving submissions outside of the upload
process. So that it  only occurs once and then we don't have these
millisecond type issu

**Comment by ryoung2512** [comment]
Sorry, forgot to update this. We were able to fix it by passing timestamp through the header client side. We currently however always store the files. This can be changed.
