### ISSUE TITLE
IFS->Tool Type Selection

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#144]
The ability to select programming or writing tools from the tool page. Near the top of the page.

I know this was recently added but should be removed as it would be confusing to all potential disciplines except CS. It could be potentially displayed if a student is in multiple courses and across disciplines.

Ex) Don't show if only in CS
       But show it if a student is in CS and another course (ex PSY).

This will become more of an issue as we move into more disciplines possibly this summer.

**Comment by ndomenic** [comment]
I could just comment out the code that displays this to the user for now, but I believe that having the choice will be good for students who want to use the tool but are not enrolled in any courses. You can't really say for sure if the users are necessarily going to be enrolled in a course that is setup for IFS. Preventing this choice would essentially lock out a decent amount of potential users.

**Comment by ian-james** [comment]
Well, we will have the code in GitHub so it's ok to just remove.

We likely won't have many that don't enroll in a course since we're targetting specific courses. But they also have the option to switch in preferences too. We could add that too the preference page that the user sees when they first login.

The downside of having it is that you always have to see it even if you're only going to use one set of tools.

**Comment by GrantDouglas** [comment]
Removed
