### ISSUE TITLE
Refactor-> "Programming" and "Visual"and "Writing" constant 

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#148]
The session is storing "Programming" or "Writing" or "Visual" tools information throughout IFS
This needs to be refactored into the tool menu json so that it can be extracted when a tool is select.
It needs to be handled in general throughout IFS.

**Comment by ryoung2512** [comment]
Can we get a little more detail on this, please?

toolList.json already stores runType as either "writing", "visual" or stats
toolListProgramming.json stores runType as "programming"

Seems to us that we could just fetch the runType straight from the JSON file. Is that what you want?

Tagged Kevin so he can follow this as well.
@kglovern

**Comment by ian-james** [comment]
You'll see a lot of checks for if tool is programming or writing written even as constants throughout this was the quickest way but is terrible. Especially, as the scope expands to potentially have "Geography" and "Engineering" tabs.  

So quick and easy thing that was being done is at least create one function to check isProgramming. I believe that was in Constants but never finished or used...can't remember which.

For the 2nd part, I'm thinking that we could extend the fields in menuJSOn to be perhaps more specific to the field. As stats is already in both CIS and writing and if documentation programs start to make their way into the IFS then maybe would have CIS - writing or CIS documentations.  Basically, just thinking we should differentiate between runType and discipline. 

I'm also thinking about course instructors might want to limit some of these options so that not all tools are available too.

**Comment by ian-james** [comment]
Removed the constant files and stores in a configuration file. Small changes to the code to follow.
