### ISSUE TITLE
Associating Feedback items with specific Assignments

### ISSUE THREAD

**Issue by kglovern** [ian-james/IFS#155]
One of the changes that came up with discussion today was that there should be an option to associate feedback items/uploads with a particular assignment for a course that student is enrolled in.

This feature would be opt-in - the student could select (and the default would be) no associated assignment.  Otherwise, they have an option to associate a tool feedback session with one specific assignment.

**Reasoning**:  Allows further feedback/statistics for instructors and students, allows more tailored engagement feedback to users

**Design Decisions**
Where in the current workflow would this selection sit?

**Current workflow:**
User logs in, is presented with list of tools
Can select/deselect tools and upload a file or files
User clicks feedback, is presented with modal while feedback processses and optional pulse option
Once parsing is complete, user can click "See Feedback" to read all feedback items for the files(s)

**Options:**
Few ideas spitballed during the discussion:

1) Dropdown-select at top of tool page - select an assignment/none for courses user is related in
_Cons_ - may get lost - there's already a lot of options on this particular page to choose from currently

2) User sets "focus" when they first login to system (assignment) which persists until changed.  They either select a particular assignment for this session (which could be changed) or "No Focus".  This value is used for all feedback submissions for this login session
_Cons_ - extra step for the user each time they use the system (even with default value), might lead to issues/confusion when submitting for two different assignments in one sessions, etc.

3) User selects associated assignment on feedback processing modal
_Cons_ - Also sort of busy in terms of options (view feedback, pulse option, select assignment all in one modal)

4) Checkbox near the "Upload Files" button that asks whether they want to include this as feedback item.  If checked, they then select an associated assignment
_Cons_ - two steps instead of one (users are lazy)

**Comment by GrantDouglas** [comment]
Finished and debugged
