### ISSUE TITLE
Tool state becomes out of sync

### ISSUE THREAD

**Issue by kglovern** [ian-james/IFS#159]
### Description
Tool toggle on development development branch becomes out of sync since the change to all tools always being off for a new session

### Expected behaviour
Toggle tools on, upload file, view feedback.
When I go back to upload, all tools should be toggled off and the options for each tool hidden

### Actual behaviour
Tool options are expanded and still on, despite the tool toggle being in the off state.  Clicking to turn the tool on results in the tool options being hidden instead of shown.

#### IFS Version
0.3 - development branch

#### Browser
Please tick the affected browsers.

 - [ ] Chrome/Chromium-based
 - [x] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

**Comment by GrantDouglas** [comment]
Fixed for now by setting all tools to be off
