### ISSUE TITLE
IFS submission system cannot handle text files without extensions

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#2]
![screenshot from 2017-03-02 14-45-57](https://cloud.githubusercontent.com/assets/6888381/23524043/ff1ab038-ff56-11e6-9398-0a30f62bcfde.png)

**Comment by keeferrourke** [comment]
Look into checking for and accepting certain file *mimetypes* rather than extensions?

**Comment by ian-james** [comment]
Took a quick look at this will fix later, so mostly for my own notes.
fileUploadConfig:fileFilter is throwing this error based invalid extension type but it isn't handled in next()
Need to catch this error somewhere.

mimetype checking is a good (re)inclusion

**Comment by ian-james** [comment]
Believe this to be fix. Mind confirming Keefer. Thanks

**Comment by keeferrourke** [comment]
Attempting to upload [testNoExt](https://github.com/ian-james/IFS/blob/master/ifs/tests/testFiles/testNoExt) yeilds the following on my machine:

![screenshot from 2017-05-05 18-13-48](https://cloud.githubusercontent.com/assets/6888381/25766142/a7368c44-31be-11e7-9ca3-3b77c13a7e30.png)

Is this the desired result?

**Comment by keeferrourke** [comment]
Looking to close some issues. @ian-james is this what is supposed to happen?

**Comment by ian-james** [comment]
This is fixed at least functionality.
I've improved the message a bit based on which type of tools the user is using.

The message itself might need to change later but we can close this.
