### ISSUE TITLE
'undefined Tool Screen' on first log in for new user

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#20]
Upon creating a new user and logging in, the tool screen shows programming tools with an 'undefined' header. This is probably bad from an UX standpoint, but is an extremely minor issue.

First noticed Thurs 04 May 17 around 14:30.

![screencapture-localhost-3000-tool-1493954805937](https://cloud.githubusercontent.com/assets/6888381/25733589/9cf15228-3128-11e7-95e9-65d0618abae0.png)

**Comment by ian-james** [comment]
Believe if this related to #21

**Comment by ian-james** [comment]
Should be fixed, related to typo.
Longer term this should be moved to part of user preferences.
