### ISSUE TITLE
Preferences aren't saved across sessions

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#29]
We should really consider how to save user preferences across sessions.

The first thing that comes to mind for me is to create a saved preferences JSON file for each user, somewhere that is easily accessible by any page that needs it. This way we could allow a user to easily set preferences, and not have to reset them. Perhaps under `users/username/saved-prefs.json`; a page could make a GET request to the relevant controller which would read that file and send it back. Unfortunately, I'm not really entirely sure how user management is done...

This should become necessary as we populate the preference page with more options.

We discussed adding the option for configurable code-colourschemes to IFS, which is something I would like to do so that users can have pretty feedback pages. There are lots of themes over at https://jmblog.github.io/color-themes-for-google-code-prettify/ which we can use easily (as they are installable as an npm module). This, among other undiscovered options could be easily added once Preferences is revamped :smile:

**Comment by ian-james** [comment]
Great find with the themes!

I think the preferences json files would work and be easy to handle. My concern would be including scalability and analytics.

My initial plan for preferences was to create a database table that held all the information, potentially even having a preference modification ID to track how many changes occurred and what changed. It would be easy enough to add the retrieval and preference updates to different routes via app.use(). I think the benefit of DB storage would also be in comparing students preferences. Although, I do think preferences are better suited for JSON that mysql.

Not saying start implementing this yet, but eventRoutes.js has an example of preloading a request with information before a specific app route (tool, feedback..etc) is called. I'm also reducing code redundancy for database function in the EventTracking branch...might not be pushed yet.

**Comment by keeferrourke** [comment]
Awesome! You're right that using a preferences database might be better for analytics purposes, since this would allow us to store the number of times a particular preference is toggled, and also how many times a user used a given option for the preference. I'm entirely sure how useful this data would be, but someone might like to have it.

I was thinking of JSON for simplicity, and totally forgot about the data collection aspect to this. Good catch :D

**Comment by keeferrourke** [comment]
I opened a new issue ( #37 ) about the preferences redesign.

**Comment by keeferrourke** [comment]
I think this has been solved?
