### ISSUE TITLE
[Tools] Feedback page bugs

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#31]
Here is a video which highlights some of the bugs I've encountered, and will attempt to explain here: https://krourke.org/files/ifs_feedback.mp4

Firstly, when selecting both the spell checker and the grammar checker tools, it seems that (at times, but not always) the grammar checker does not appear in the list of selected tools.

Secondly, toggling back and forth between "all" and "spell checker" options in the tool list repeatedly seems to break highlighting. Navigating back in the browser history a bit fixes the problem.

**Comment by ian-james** [comment]
First off, nice capturing the error will have to check that tool out.

For number one, if the tool doesn't generate feedback it won't be available in the list. I noticed when you scrolled the full feedback table. Grammar tool didn't have any feedback.  I'm not saying #1 isn't a bug, it  could very well be.

Number 2, never checked that and don't have any immediate ideas on it.

**Comment by keeferrourke** [comment]
Okay great! I'm glad number one isn't a bug. I'm wondering if it would be better from a UX perspective to still show the tools that were selected but didn't generate any feedback, and simply grey out and disable the relevant option in the `select` form element.

Displaying a message like, `{{ tool.displayName }} didn't catch any errors!` might also be nice feedback :grin:

**Comment by keeferrourke** [comment]
I believe as of commit https://github.com/ian-james/IFS/commit/fb694f81de64af8fd43cd43a5b2f162822a6fc25, all problems with the Feedback page have been fixed.
