### ISSUE TITLE
Improve UI for Feedback page

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#32]
I opened this issue (converted from a project card) so that we can track the changes made to the Feedback page.

Below is what @ian-james wrote on the card (slightly paraphrased)

- [x] This page will need to have the sidebar cleaned and polished.
- [x] The size and format of the cards need to be adjusted.
- [x] Tool Selection drop-down placement and sizing needs to be adjusted.
- ~~implement pagination for some tools with long text files (?)~~

**Comment by keeferrourke** [comment]
I have mostly addressed points 1 through 3 on the `ui-dev` branch. I am not sure what is meant by tool pagination, or how to implement it.

**Comment by ian-james** [comment]
Requested Change: links to visual tools that have feedback.
Ie word cloud and text summarization.

I'm not sure we need number 4, max essay size for students is 5 pages. Although people will probably test with larger files not sure we will need to put effort toward that this term.

**Comment by keeferrourke** [comment]
Updated first post on this issue.

Also relevant:
- [ ] show all enabled tools in dropdown on Feedback page
   + clicking a visual tool should cause redirection to the appropriate page on form submittal
- [ ] add other syntax highlight colour schemes (related: #37, mentioned in: #29)

**Comment by keeferrourke** [comment]
Latest commits to master from 'dev' now show visual tools on the feedback page.

Next on this issue: syntax highlighting colour schemes. Since this is an issue of aesthetics at this point, I am changing the priority of this issue to low.

**Comment by ian-james** [comment]
Closing because this issue is a little too generic and has grown in scope.
We've (You've) accomplished the original main issues.

Syntax highlight color scheme is now captured in another issue.
