### ISSUE TITLE
Revamp Preferences

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#37]
We will be making preferences persistent across sessions by storing them in a relational database.

I believe that the available options should still be populated on the page from the `preferences.json` file, as this allows us to specify templated options for `select` elements quite easily. Querying the preferences database would then allow us to pre-fill out the form with the currently active options.

New fields that the preferences form should handle are:

- [x] Toolset preferences (Programming, Writing)
- [ ] Code highlighting colourscheme (see https://jmblog.github.io/color-themes-for-google-code-prettify/ for a list of themes, it would likely be sufficient to store the name of a given theme in the User Preferences database)
- [x] User's real name (text entry box, store the string in database)
- [ ] User's email address
- [x] User bio
- [x] Profile avatar
- [ ] Class enrollment (an array, of length one or more)

The revamped preference page should also allow a user to upload either a PNG or JPG file to display as their avatar on their profile page. See issue #36 for more details on proposed design and discussion on implementation.

**Comment by ian-james** [comment]
Preferences now handle all tools and options.
The code themes are currently the only thing not saved but are easy enough to do as it's implemented.

I could see the rest of the information falling more into a profile class than preferences, although perhaps it would still be shown on the preference page.

**Comment by keeferrourke** [comment]
@ian-james I think just from a usability perspective, it might be easier if all preferences are kept together on the same page. Not totally sure though.

**Comment by ian-james** [comment]
Sure, we can have them all in one visual place especially since we have like 6 items :)

**Comment by ian-james** [comment]
Closing this because of too large of scope. We've accomplished the main objectives of this issue. I think the only remaining issue is add/remove class which I"ve captured in a new issue. Changing student's email could be useful for long-term users, it's unlikely to change over the course of the experiement so I've excluded it.

**Comment by keeferrourke** [comment]
Class enrolment/unenrolment has been mostly implemented, but I have yet to push the code. Expect it tomorrow unless I say otherwise :)
