### ISSUE TITLE
[Performance] Tools are *slow*

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#43]
Notably, grammar and spelling tools are extremely slow to process files with a large number of mistakes (~700 mistakes can take almost 5 minutes to process on a 3rd gen core i7). Something needs to be done to fix the performance hit. Server-side, I believe this is currently handled by a request timeout.

Basically, I think the spelling and grammar tools need to be refactored to take advantage of parallelization through multiprocessing/threading.

I'm going to take a look at this today to see if I can resolve the performance issues, and will update on this issue as I tackle the problem. Never seriously dealt with parallelization in Python before though, so this should be fun.

[to investigate]
Info relevant to server configuration &mdash; do we know how many cores/threads are available at sat.socs.uoguelph.ca? Is there an easy to detect this information to optimize these tools from the installation script?

**Comment by keeferrourke** [comment]
Hmm. Slight problem. sat.socs.uoguelph.ca only has one virtual cpu with one thread. Multiprocessing probably will not be helpful on the current server, since there are no additional threads to take advantage of....

```
$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            6
Model:                 2
Model name:            QEMU Virtual CPU version 2.1.2
Stepping:              3
CPU MHz:               2814.368
BogoMIPS:              5628.73
Virtualization:        AMD-V
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
NUMA node0 CPU(s):     0
```

**Comment by ian-james** [comment]
Keefer has contacted Guelph CS help to get the server upgrade.We now have a second CPU not sure if that will be enough. Bare minimum I expected was two CPU for website and Job Queue, we will have to see how the performance is with more testing. Siege is apparently a good tool for load testing.

This issue likely isn't closable but needs further investigate to make our case for additional resources.

**Comment by ian-james** [comment]
Closing this until we do more rigorous testing with SIEGE.
The 2nd core has improved performance greatly. Hopefully, hardware upgrades are accessible.
