### ISSUE TITLE
Cross-Browser Testing

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#47]
Heading into beta, we should be testing various system/browser configurations to make sure that IFS works everywhere.

In development, I've found that IFS works in Chromium and Firefox based browsers (including on mobile), but haven't tested others. Any issues with browser configurations should be referenced here.

IFS has been tested on:

- [x] Chrome/Chromium (blink-based)
- [x] Firefox/Icecat (gecko-based)
- [x] Safari (webkit-based)
- [ ] Internet Explorer
- [x] Microsoft Edge
- [ ] others?

**Comment by ian-james** [comment]
Browser Usage Stats:
       Chrome   IE            Firefox       Safari   Opera
April	75.7 %	4.6 %	13.6 %	3.7 %	1.1 %

**Comment by ian-james** [comment]
You will likely want to investigate most popular versions of the browsers too.

**Comment by keeferrourke** [comment]
> We will likely want to investigate most popular versions of the browsers too.

Good point, I know that Firefox maintains three versions of their browser: the LTR (long-term release, aimed at businesses and less tech-savvy users), regular, and nightly (dev/experimental) builds.

Chrome similarly has Canary (nightly builds) and standard releases. Chromium doesn't have official binaries as far as I know, but most GNU/Linux distros try to keep Chromium versioning in sync with Chrome (i.e. make releases from the same point in the source tree).

**Comment by keeferrourke** [comment]
Mentioned in meeting today:
 * need to test support for IE and Safari; if IE is a problem, just put a message on the log-in page to tell users to use a different browser :grin:

**Comment by keeferrourke** [comment]
[uikit](https://github.com/uikit/uikit) claims to support Edge and IE10+

**Comment by ian-james** [comment]
Took a quick look at IE11, many things appear to work. However, a glaring issue is that footer doesn't get placed properly so it actually takes over the position of the navbar. Found a couple other bugs related to sticky footer's in IE.

**Comment by keeferrourke** [comment]
Looks like Internet Explorer doesn't treat `flex` displays the way it should.

https://stackoverflow.com/questions/21600345/flexbox-and-internet-explorer-11-displayflex-in-html

We should take at look at playing with the flex values in `app/shared/views/css/main.css`. If there isn't a cross browser solution, we can probably just make the footer non-sticky. Stickiness just makes the webpage look nicer when the display is taller than the content, which on most routes and devices is going to be pretty rare.

**Comment by keeferrourke** [comment]
I don't currently have a Windows computer, but am getting a new machine in about 10 days. I'll see what I can do about resolving sticky footer issues in MS Edge when I get.

**Comment by keeferrourke** [comment]
Currently performing some tests on Windows 10 and macOS Sierra.
1. MS Edge appears to render the IFS just fine
2. IE 11 doesn't know how to deal with the footer properly; this is likely an issue with Internet Explorer using non-standard defaults for flex elements.
3. Safari appears to render the IFS just fine.

**Comment by keeferrourke** [comment]
As of commit 16bce7662304a103a77272535966971fd4ca0e89, sticky footer is working properly on Internet Explorer 11.

I do not have a means for testing compatibility with IE10 or below, and I believe that nearly every internet explorer user is now on IE11+/Edge at this point.

Closing this for now, since it appears that every major browsing engine works properly (IE/Edge, Blink, Gecko, Webkit)
