### ISSUE TITLE
Signup=>Preferences

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#49]
Preferences field name should be populated with student name  or be called alias or preferred name.

This occurs directly after sign-up.

**Comment by ian-james** [comment]
Should be resolved as of commit ce2bc56

**Comment by keeferrourke** [comment]
There may be a conflict with commits I will be pushing tomorrow; I'll have to take a look here.

In [ ifs/config/preferencesList.json](https://github.com/ian-james/IFS/commit/ce2bc5635a798a80738aca2255f9084f1070e3b7#diff-2e1e9f681cb88d29bad901ab91c4f9d7), you have changed 'Full Name' to 'Alias'; in work that has yet to be committed, I have changed this string to 'Preferred Name'. Is 'Alias' the preferred language?

**Comment by ian-james** [comment]
I almost changed it to preferred name actually but choose alias thinking it
could be anything. Preferred name is a good option here so you can
overwrite.
