### ISSUE TITLE
Add Student to Course

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#52]
Just want to make sure this is captured but currently.

Student's are unable to connect to one or more courses.

This is likely part of the "IFS" startup process. #

**Comment by keeferrourke** [comment]
Working a patch to add course enrolment/unenrolment from preferences.

**Comment by ian-james** [comment]
Alright, that works for students to update later on. 
We will want to add that as part of the startup but preferences is good quick way to get it in IFS.

**Comment by keeferrourke** [comment]
Once I have the code for the preferences course enrolment form pushed, I'll get a post-registration module started that encompasses initial course enrolment / preferred name corrections / agreement to terms, etc.

**Comment by keeferrourke** [comment]
Closing this issue because I believe that issue #59 better encompasses the problem at hand. Students can enrol/unenrol from courses as of commit 6eac2106469380dbb1e5516e1b791d725b6f2c8e.
