### ISSUE TITLE
[Feedback] Programming Feedback General Statistics

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#55]
Statistics that come to mind for programming-type files, are:
 * Number of lines of code
 * Number of blank lines
 * Number of lines of comments

These can be handled by [cloc](http://cloc.sourceforge.net/) (installable from Ubuntu universe), which *does* have a nice JSON-to-stdout output option.

```sh
cloc --json ./path/to/submission/dir
```

If it is reasonable to add cloc as a dependency, then we can make use of it in `feedbackParser.js` when the submission type is "programming".

**Comment by keeferrourke** [comment]
Tentatively taking control of this issue since all my assigned tasks have been completed.

**Comment by keeferrourke** [comment]
... on second thought, I can't seem to puzzle through how Writing Statistics are generated and stored in the database, so I don't think I can reproduce this functionality using the `cloc` tool.

**Comment by ian-james** [comment]
Writing the tool should be easy enough but I don't want any new features in before the meeting tomorrow. So if you do finish don't commit it.  

I think our major task is now identifying bugs and doing performance testing. Siege is actually awesome and super easy to get started. I've run the most basic examples and it's already been useful.

**Comment by ian-james** [comment]
Tomorrow we could talk about how the writing stats work if you want.

**Comment by ian-james** [comment]
We have to make a case for those extra resources and smoke test our system.

**Comment by keeferrourke** [comment]
Makes sense!

**Comment by ian-james** [comment]
This has been integrated in a couple tools now.
