### ISSUE TITLE
[Preferences] Allow student to change course selection.

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#57]
Students should be allowed to add or remove themselves from classes in the preferences.

This also needs to be part of the initial new account setup.

- [x] Class enrollment (an array, of length one or more)

**Comment by keeferrourke** [comment]
I have class  enrolment/unenrolment partially implemented as a secondary form on the Preferences page. I'll be pushing the full implementation tomorrow; and following up with a solution for enrolment during registration.

**Comment by keeferrourke** [comment]
Should be fixed as of commit 6eac2106469380dbb1e5516e1b791d725b6f2c8e.
