### ISSUE TITLE
[Skill-Matrix] -> Students ability to modify their self-assessed skills

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#58]
Need a page where students can observe their skill scores
and modify them if they wish.

**Comment by keeferrourke** [comment]
This should go in the Dashboard I believe?

**Comment by ian-james** [comment]
I'm open to suggestion on where this goes.

SO far for the dashboard, I'm planning on having:

1) Daily Focus ( Select the assignment you're working on). This help us
link their activity to a specific task.
2) Student Stats and Social Stats. A couple super highlevel stats about the
user base.
3) Upcoming events ( likely move this out of profile)

I could see this be an occasional section in the dashboard like when the
daily focus is resolved.

**Comment by keeferrourke** [comment]
Moving the  events from the profile will make the profile page largely empty; I had envisioned  the profile to be an overview (information at a glance) while the Dashboard would be something that shows a significant amount more detail (as you mention in points 1 and 2).

If we move Events out of the profile, that page will be mostly empty; is there something that could replace them on the profile, or would the profile be largely rendered useless?

**Comment by ian-james** [comment]
Alright, I've kept the upcoming events in profile. I have moved some of the skills into the dashboard though, I think we can have those in both places. Like profile could have your top skills and dashboard could have in-progress skills, even if there is overlap not a big deal.

**Comment by ian-james** [comment]
Skill Link has been added to the dashboard. Students now have a separate page to evaluate their skills based on the assignment. Only task left is hook up to event tracking.

**Comment by keeferrourke** [comment]
Awesome! I will update my local copy and take a look at this. I just sent you a sort-of-related email; if I addressed something that you have already taken care of &mdash; feel free to ignore it.

**Comment by ian-james** [comment]
This should be all set up.
