### ISSUE TITLE
[Bug] Profile does not populate if student is not enrolled in classes

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#61]
### Description
Student profile page is not populated with profile information when the user is not enrolled in any classes. Name, bio, classes are empty.

### Expected behaviour
The student profile page should populate with the name and bio. The classes section should show a link to preferences to encourage a student to enrol in a class.

### Actual behaviour
The profile was not populated properly

### Steps to reproduce
 1. Log into IFS.
 2. Go to /preferences
 3. Unenrol yourself from all classes
 4. Go to /profile

### Suspected cause
The StudentProfile component attempts to populate the profile with the getStudentProfileAndClasses() query which returns an empty set if the student has no classes. 

### Solution
Profile info and class information should be populated with separate queries / json objects.

**Comment by ian-james** [comment]
FIxed this is in my latest commit. 
Added note in code as to reason the bug occurred. Note can be removed.
