### ISSUE TITLE
Connect Registration to Surveys

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#65]
As soon as the post-registration process is completed, it needs to be linked to the survey system to disable surveys that were not accepted by the user and also not relevant to the user based on their tool selection.

**Comment by keeferrourke** [comment]
The post-registration set up system has been implemented as of commit https://github.com/ian-james/IFS/commit/87a656bbed10f362810dcfe3f82f41db2eab6051. The surveys system is likely concerned with the `user.optedIn` property, which can be used as a master switch for turning surveys on or off.

`app/components/Setup/userOptDB.js`'s `getUserOptIn()` method returns the relevant values.

**Comment by ian-james** [comment]
Survey's should now be integrated with opt-in and opt-out action.
