### ISSUE TITLE
Dashboard Polish

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#67]
The dashboard could really use the excellent polish you've provided to the rest of the IFS. 
I'm hoping you can fix it up to look a little aesthetically pleasing and attention grabbing.

**Comment by keeferrourke** [comment]
I don't think is going to be updated by the pilot for the software, but I can certainly attempt to clean up the dashboard next week :smile:

**Comment by keeferrourke** [comment]
See commit 354b289 for the dashboard redesign. The dashboard has been streamlined, data is represented in a clear card-based format, and duplication of many profile elements has been removed. Pending other changes, this will mark v0.0.3.
