### ISSUE TITLE
Add email verification and password recovery functionality

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#69]
or alternative method as needed.

**Comment by keeferrourke** [comment]
As mentioned before: [email-verification](https://www.npmjs.com/package/email-verification) seems to be the easy way of doing things. Caveat: it seems to require Mongo DB.

It needs to be investigated whether this module can be used with SQL, otherwise we will need to find (or create) another solution.

**Comment by keeferrourke** [comment]
Another possibility might be a process outlined below:
#### pre-requisites
 1. use [nodemailer](https://nodemailer.com/about/) for email communications
 2. create a new  database for storing information about temporary links; it might be something such as the following for instance:

    | Field  | Type    | Description                                     |
    | ------ | ------- | ----------------------------------------------- |
    | userId | Integer | The UID for whom a temporary link was generated |
    | link   | String  | Either 'verify' or 'reset'                      |
    | token  | String  | Randomly generated alphanumeric                 |
    | expiry | Date    | The time that the temporary link should expire  |

### implementation
 1. create POST/GET routes for `/verify` and `/reset`
 2. when a new user completes registration, create the user as normal, but prevent log in until a new boolean `is_verified` is set in their respective database entry
 3. upon registration (ex for UID 42), create the new user and:
    - generate a random alphanumeric token
    - `INSERT INTO verify (userId, link, token) VALUES (42, 'verify', foobar);`
    - send an email to the registration address containing a link of the format: `example.com/verify?id=42?token=foobar`
    - when the user visits this address, then a bool in the user table `is_verified` should be set to TRUE and the user should be shown a "success" page on the `/verify` route
    - `DELETE FROM verify WHERE userId=42 AND token='foobar';`
    - after 10 seconds, redirect to IFS's homepage at `/`
 4. upon a request to reset the password:
    - generate a random alphanumeric token
    - set an expiry date to 24 hours from the current time
    - `INSERT INTO verify (userId, link, token, expiry) VALUE (42, 'reset', whizzbang, $EXPIRYDATE);`
    - send an email to the user's address containing a link of the format: `example.com/reset?id=42?token=whizzbang`
    - when the user visits this address, verify that the link has not expired; if it has expired then: `DELETE FROM verify WHERE userId=42 AND token='whizzbang';` and show an error
    - if the link is valid, then show them a form where they must enter a new password; update the password for the user on form submittal
    - `DELETE FROM verify WHERE userId=42 AND token='whizzbang';`
    - show "success" page, and redirect to `/login` after 10 seconds

**Comment by keeferrourke** [comment]
Finally getting started on this. Experimental server set-up is taking a while longer than I thought, so in the mean time I'm tackling some smaller issues.

**Comment by keeferrourke** [comment]
TODO on this issue:
- [ ] Implement email system
- [ ] Generate verification links (indicated by type='verify' in config.verify_table)
- [ ] Validate verification links against database
- [ ] Adjust log-in system to disallow log-ins without first completing verification
- [ ] Generate password change links (indicated by type='password' in config.verify_table)
- [ ] Validate password change links against database
- [ ] Allow user to update their password

**Comment by keeferrourke** [comment]
TO TEST:
- [ ] expired token management:
    + MySQL event should delete unactioned tokens from the databases after ~12 hours (event runs every one hour, checking for tokens that were created >12 hours before hand)

**Comment by keeferrourke** [comment]
Everything on this issue complete. TO DO for testing:
- [ ] ensure that MySQL event manager actually deletes reset requests after 12 hours.
  + problems were encountered in that mysql 5.7 does not enable the `event_scheduler` by default on Ubuntu; the install script now enables this in the system configuration, and the Logger warns about the event scheduler every time `createDatabases.js` is run.

Once this has been verified to be working, I will merge the 'account-verification' branch to master.
