### ISSUE TITLE
`npm test` fails on Debian Jessie

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#7]
After installing IFS and all its dependencies on a fresh Debian Jessie server, IFS cannot be run. Strangely, no such problem is to be had on a fresh Ubuntu Xenial installation.

Testing was done with an automated installation via the installation script that I added in commit 8a5574ae4e2252c0aa75bc4a3356227020f309a5

Here is the console output on the errors:
```
# npm test

> ifs@0.0.0 pretest /path/to/ifs
> node ./config/createDatabase.js


/path/to/ifs/config/loggingConfig.js:19
const tsFormat = () => (new Date()).toLocaleTimeString();
                  ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path/to/ifs/config/createDatabase.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by ian-james** [comment]
I'm guessing that is related to server having an older version javascript
standard.
That syntax is available as of ECMA 6, so might be related to older node
version.

**Comment by keeferrourke** [comment]
yeah, looks like `npm` is frozen at `v1.4.21` on Debian Jessie but it's at `v3.5.2` on Ubuntu Xenial.
Probably going to have to look into running the latest version of npm/node on Debian, since jessie-backports doesn't have anything newer either.

**Comment by keeferrourke** [comment]
Commit 6168e3c784e15438eb49417decebd8a75859e731 should resolve this issue on both Debian and Ubuntu automated installations.
