### ISSUE TITLE
[Bug] Sessions die too quickly

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#73]
### Description
Sessions don't seem to last more than 3 minutes.

### Expected behaviour
Sessions should last 30-60 minutes without activity

### Steps to reproduce
 1. Log into IFS.
 2. Do nothing.
 3. Get logged out automatically.

#### IFS Version
v0.0.0

#### Browser
Please tick the affected browsers.

 - [x] Chrome/Chromium-based
 - [x] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [x] Other (Please write below)
   + GNOME Epiphany

**Comment by ian-james** [comment]
Issues should be fixed but leave open for longer testing.
