### ISSUE TITLE
Wordcloud matches things that are not words

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#74]
### Description
The word cloud at times matches character sequences that are not words.

### Expected behaviour
Only words that match the pattern `\w+` should be displayed in the cloud.

### Actual behaviour
![word-cloud-fullpage](https://user-images.githubusercontent.com/6888381/28049389-367b2448-65c5-11e7-9ae6-b05b320772b4.png)

**Comment by ian-james** [comment]
Closing, haven't observed this isn't previous commit.
