### ISSUE TITLE
[Bug] Text Summarization breaks if more sentences are selected for the summary than in original file

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#75]
### Description
IFS hangs when small text files are submitted and too many sentences are selected for a text summary.

### Expected behaviour
The feedback should be shown anyway, and the text  summary should either show nothing, or show the original text.

### Actual behaviour
IFS sat around processing files for a long time, then failed to process the textSummarization job.

### Steps to reproduce
 1. Log into IFS.
 2. Select Writing Tools in /preferences
 3. Enable 'Text Summary' tool
 4. Select 10 sentences in the summary
 5. Upload a file with fewer than 10 sentences
 6. Wait forever.

**Comment by ian-james** [comment]
I can't reproduce this can you paste text or upload test file. I've tested both tool and IFS with Text Summary.

**Comment by keeferrourke** [comment]
I can't seem to reproduce this any more either. I have updated the server configuration since submitting this bug report, so it may have been cause by improper handling of dependencies. I will investigate this further.

**Comment by keeferrourke** [comment]
Closing this because it's no longer reproducible.
