### ISSUE TITLE
[Bug] Database errors when student not enroled in any classes

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#77]
Student's must be enrolled in a class.

Alternatively, any student not in a class needs to be assigned to a no-class class, this will stop all the database errors that assume a student is in a class.

**Comment by keeferrourke** [comment]
I'm not sure how to fix this without doing something potentially bad and hacky like creating a "null" class as the first entry in the class table immediately after installation, ensuring that every student is automatically enrolled in this class, then filtering out this class on the course enrolment page on `/setup`.

Would it be more feasible to drop the assumption that a student belongs to a class?

**Comment by ian-james** [comment]
I'm thinking we add an other class to DB as 'other'. Then when students that go through the enrol page we require them to select one of the of the 3 classes. It's much easier for the stats if they at least have an id for the class. Plus, we get rid of them continuing on without accidently selecting a class.

**Comment by ian-james** [comment]
We have added additional classes. CIS3750 and CIS 1500. 
Need an not enrolled in a class but want to use the tool ( as a default required option)

**Comment by ian-james** [comment]
Closed other task related to this not necessary.
