### ISSUE TITLE
[Bug] Feedback table showing extra output

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#78]
### Description
When there is feedback for multiple tools available (ex. gcc, cppcheck), and we only want to see the feedback from one tool (ex. cppcheck), the feedback table still shows entries for GCC, but with blank targets.

### Expected behaviour
Unselected tools should not show in the feedback table unless showing 'All' feedback.

### Actual behaviour
![ifs-feedback](https://user-images.githubusercontent.com/6888381/28239983-5ba17fe0-6946-11e7-874c-4254982bdfb8.png)

### Steps to reproduce
 1. Log into IFS on https://sat.socs.uoguelph.ca
 2. Select programming tools
 3. Enable GCC, Clang, and Cppcheck
 4. Upload ifs/tests/programmingTests/unzippedTar.tar.gz
 5. In the feedback selection dropdown, choose cppcheck
 6. Notice that the file is correctly marked up, but the feedback table shows extraneous, incomplete entries.

### Notes
I believe this issue was introduced by recent commits, unless I just didn't notice previously.

#### IFS Version
v0.0.1 (as of at least commit 7704c679f35827d8476165110ae0143a011c093e)

#### Browser
Please tick the affected browsers.

 - [ ] Chrome/Chromium-based
 - [x] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

**Comment by ian-james** [comment]
This should be fixed in upcoming.

**Comment by ian-james** [comment]
Can now filter results by tool type.
