### ISSUE TITLE
Zip files not accepted

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#79]
### Description
Please include a detailed description of the bug or error you encountered.

Noticed that testing zip file does not upload to the IFS site. Might be the difference between Linux/WIndows based zips

### Expected behaviour
Zip should upload an unpack

### Actual behaviour
Error message about file types not being accepted.

### Steps to reproduce
 1. Log into IFS.
 2. Upload page
 3. Pick testfile for zip files.
 4.  Error message received indicate zip is ok.

#### IFS Version
v0.0.1

#### Browser
Please tick the affected browsers.

 - [x] Chrome/Chromium-based
 - [ ] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

**Comment by keeferrourke** [comment]
Was the zip created on Windows? I may have accidentally broken zip support when I added PDF support... lol. Should be relatively easy to fix hopefully, I'll take a look tomorrow morning.

**Comment by ian-james** [comment]
I was using the Testing Example Zip from test files. I can't recall where
it was zipped, I believe Linux but not 100%

**Comment by keeferrourke** [comment]
I can't seem to reproduce this issue. Using the IFS testing zip file, I have no issues whatsoever on localhost of my machine.

See: https://krourke.org/files/ifs-zip.ogv

**Comment by keeferrourke** [comment]
Just checked out the SOCS server. Attempts to upload zip files were failing because the program `unzip` was not installed on the machine. This dependency is added to the install script as of commit d7de0bf.

**Comment by ian-james** [comment]
Sorry forgot in my haste to indicate this error was only on sat.socs
Weird, pretty sure I had tested zips earlier and it works perhaps that was when using a different unzip technique.

**Comment by keeferrourke** [comment]
I was fairly certain of that as well... yet, unzip was missing. Regardless, the issue is fixed now :)
