### ISSUE TITLE
[Preferences] Profile Bio field has preset value

### ISSUE THREAD

**Issue by iam4722202468** [ian-james/IFS#81]
### Description
In preferences, 'profile bio' field is filled in with text (Value attribute)

### Expected behaviour
Text should instead be a placeholder (Placeholder attribute)

### Actual behaviour
Value attribute is set for empty field

### Steps to reproduce
 1. Log into IFS
 2. Go to preferences
 3. Look at profile bio field

#### IFS Version
IFS v0.0.1
#### Browser
Please tick the affected browsers.

 - [ ] Chrome/Chromium-based
 - [x] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

### Description
Generally fields like this use the placeholder attribute instead of the value attribute

### Implementation
When setting text, change attribute from value to placeholder

**Comment by ian-james** [comment]
Removed default bio and set to blank As of  5135ffa
