### ISSUE TITLE
Student Voting on Useful Feedback

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#82]
The ability to up and down vote feedback this will come into play as students personalization becomes a bigger factor in IFS.

For now the goal is show errors in a priority based on how useful other student's found the feedback.

**Comment by keeferrourke** [comment]
How do you prose this be implemented in the UI? I like this idea, but the Feedback page is already extremely cluttered. Should this go somewhere in the dashboard, where a student can see student-reported feedback/tool-error? A new route?

I imagine the up/down vote interface would look something like a Reddit post?

I worry about how useable this would be.

**Comment by ian-james** [comment]
It's likely this would receive very little attention from students.  It's actually just a matter of putting it back in since it was original placed on the "more info" feedback side bar near the bottom. It's really just a thumb up and down button at the bottom of the sidebar wouldn't really interfer. 
I'm just imagining a modal for user-input that then disappears but that part of this problem is more wishlist.

I'm still checking if I can categorize errors consistently enough to create groups of errors that students generate their own feedback with a relatively close 1 error to feedback mapping. This would be like a mini stack-overflow  and raise a lot of interesting personalization possibilities if this feature did get used. 
 It would really setup good research potential if it was used by students.

**Comment by ian-james** [comment]
+- buttons integrated on the sidebar. Wanted thumbs but didn't see it in the icon list.
Interaction is tracked as rated +- not much else is done here.
