### ISSUE TITLE
[Bug] Does not accept .cpp extensions

### ISSUE THREAD

**Issue by iam4722202468** [ian-james/IFS#84]
### Description
Error given when uploading .cpp files:
Unable to process uploaded file(s). Only tar/zipped projects and .c or .h files are accepted

### Expected behaviour
.cpp extension file should have been uploaded

### Actual behaviour
File was not accepted 

### Steps to reproduce
 1. Log into IFS.
 2. Upload .cpp file

#### IFS Version
IFS v0.0.1

#### Browser

 - [ ] Chrome/Chromium-based
 - [x] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

### Description
Program states that it works on c/c++, but does not accept c++ files

### Implementation
.cpp, .hpp, .hxx files should be added to list of accepted file types

**Comment by keeferrourke** [comment]
@ian-james This is trivial to fix, but I'm not sure it should be. The error here might simply be that we are wrongly advertising C++ compatibility for file uploads. This is your experiment, so thoughts?

**Comment by ian-james** [comment]
Yeah, this is already available via all tools so would be trivial to include. Simply need a language selection box. However, you're correct this is more incorrect advertising than anything. We haven't really tested with C++, I'll run some tests to make sure everything interacts the same way and then perhaps we could include it.

**Comment by keeferrourke** [comment]
My only concern is that `gcc` does not always behave very nicely with C++ code. For that reason, you usually compile with `g++`. I don't know how clang works with C++, if at all.

**Comment by ian-james** [comment]
I had to enable extensions in a couple locations but this was pretty easy to get going don't actually even need language option in the menu, although, we could still have one.
Clang works very similar that GCC ( maybe a little better imho ), I could upload older C++ files in the future since I used to work in that language much more often but for now it's integrated.
