### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by iam4722202468** [ian-james/IFS#86]
### Description
iam472202468 should be added to the 'Team' section on this page https://sat.socs.uoguelph.ca/about

### Implementation
Widget containing:
Title: iam4722202468
Profile Picture: either a large male gorilla or my git profile picture
Link: Github > https://github.com/iam4722202468 Website > http://scheduler.online/
Description: iam4722202468 is an undergraduate student at a university. In his free time he tests stuff.

**Comment by keeferrourke** [comment]
Nice try Ace ;P
