### ISSUE TITLE
[Bug] File upload drag and drop does not work

### ISSUE THREAD

**Issue by iam4722202468** [ian-james/IFS#87]
### Description
'Drag and drop' feature on file upload page does not work

### Expected behaviour
User should be able to drop a file in to the drag and drop section to upload it

### Actual behaviour
Browser asks if user would like to open file on client side

### Steps to reproduce
 1. Log into IFS.
 2. Go to upload screen
 3. Drop file from desktop folder to browser

#### IFS Version
IFS v0.0.1
#### Client information
Linux Mint 18 - Cinnamon
#### File manager
Nemo 3.0.6

#### Browser
Please tick the affected browsers.

 - [x] Firefox

**Comment by keeferrourke** [comment]
Noted and aware of the issue. It *does* work if you drop the file in the correct area of the box, but obviously the entire box should be droppable. Will hopefully get this fixed soon.

**Comment by keeferrourke** [comment]
Commit e945ade should fix the problem. Tested in Firefox.

**Comment by keeferrourke** [comment]
Tested to be working on all browsers except IE/Edge since I do not have a Windows machine available. Closing this bug report, but the solution should still be tested on Microsoft browsers.
