### ISSUE TITLE
[Feature Request] Multi-line Bio

### ISSUE THREAD

**Issue by iam4722202468** [ian-james/IFS#88]
### Description
User should have the ability to make a multi-line bio in Preferences > Profile Bio

### Implementation
Turn bio field in to a textarea tag, with height of around 4 or 5 lines by default

**Comment by keeferrourke** [comment]
It is my opinion that the bio section should be short. Longer descriptions should go on you're personal website, facebook, or linkedin :grin:

If anything, I would probably limit the length of the Bio field to something like 140 chars (about as long as a Tweet, iirc), to prevent over-explaining.

**Comment by iam4722202468** [comment]
Without a longer bio field it is impossible to put long copypastas, limiting user creativity and free speech

**Comment by keeferrourke** [comment]
Good thing this isn't a platform for creativity and free speech then :wink:

**Comment by ian-james** [comment]
@keeferrourke  Do something if you want with this.... otherwise close it my vote limit free speech 👍

**Comment by keeferrourke** [comment]
Closing for now. May address the character limit later.
