### ISSUE TITLE
404 Not Found at Register Page

### ISSUE THREAD

**Issue by nicholician** [ian-james/IFS#89]
### Description
When trying to sign up from the https://sat.socs.uoguelph.ca/register page, the page takes a very long time to load and eventually gives me a 404 Not Found error

### Expected behaviour
I expected to sign up and try the new tool.

### Actual behaviour
I didn't.

### Steps to reproduce
 1. Go to https://sat.socs.uoguelph.ca/register
 2. Fill in sign-up information
 3. Click Register

### System information
Running on Window 10 

#### IFS Version
V0.0.1

#### Browser
Please tick the affected browsers.

 - [X] Chrome/Chromium-based
 - [ ] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

**Comment by ian-james** [comment]
Thanks for the feedback Nico!

This appears to be related toa previous issues where the server is stuck on a zip file request. I've rebooted the server can now access the signup now.

**Comment by keeferrourke** [comment]
@ian-james was an old process that didn't know how to deal with zips still running after a whole day? A little alarming that that tied up the login/register functionality.

**Comment by ian-james** [comment]
@keeferrourke I believe it never kicks started back up. Occasionally Nodemon fails to restart it appears this was one of those times. Making a new item for heartbeat monitor and to investigate why restart failed.

**Comment by ian-james** [comment]
Closing haven't seen this again and am considering it part of an initial deployment bug.
