### ISSUE TITLE
[Ethics Review] Student Name

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#90]
Requesting student's name as part of the bio, while we're just using it for friendly user experience is part of a personal identification identifier. As such the choice to include this needs to be validated with good reason by the ethics board ....user experience might not be good enough reason.

1) Current options are keep it and remove all bio connections during the post-experiment phase.
2) Remove this feature as I don't believe we actually use the name feature anywhere at the moment.

**Comment by keeferrourke** [comment]
What was the reason this was closed? Is data being anonymized post-experiment?
