### ISSUE TITLE
[Ethics Review] Student Work

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#91]
Student submissions are currently retained with indirect connections to the original user.
Do these submissions hold any longer term value. 

The potential that students include their name in a make file or at the top of a file makes anoymizing this more difficult and perhaps we should delete their work and also save ourselves tons of space.

**Comment by keeferrourke** [comment]
If we are only concerned with the raw data we gather about the submission (i.e. number, type, frequency of errors, etc), then I see no real need to keep submissions on the server longer than the user's session lasts.

**Comment by ian-james** [comment]
That is what I'm thinking as well. Will run this by Dan and Judi to get their opinion see if there is any value in storing that information that we might be missing.

**Comment by ian-james** [comment]
After review, its best to remove all student work as quickly as possible. Latest at the end of the session, earliest previous submission.

**Comment by ian-james** [comment]
This has been integrated. Student submission folder is deleted and then readded for each submission.
Only last submission survives.
