### ISSUE TITLE
[UI]-> Stats decimal places should be capped to <2

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#93]
Dashboard is showing large decimal places for submission data stats.

**Comment by keeferrourke** [comment]
Can we truncate these values in the SQL database, or is precision important for your experiments?

The slightly more difficult solution is to truncate the values client side.

**Comment by ian-james** [comment]
I believe these are calculated  rather than directly stored. That level of precision won't be necessary for the experiments even 2 decimals places is probably not necessary.

I believe pug has a nice way of doing this where you integrate a javascript function then display. 
Depending on what is easier we could also do this before sending to pug too.

**Comment by ian-james** [comment]
Fixed in (4e37532..5135ffa) next version  for dashboard programming stats in pug. Example if need for other places
