### ISSUE TITLE
[Signup] - Character Validation

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#95]
### Description
Security report being able to input non-alpha numeric characters for account names. Nothing became of it but we should check for it and remove

### Expected behaviour
[a-zA-Z-] + any others characters

### Actual behaviour
semicolon and slashes.

### Steps to reproduce
1) Signup not sure if they're chaning data before submitting or simply submitting with cars.

#### Browser
Unsure

**Comment by keeferrourke** [comment]
> Security report being able to input non-alpha numeric characters for account names. Nothing became of it but we should check for it and remove

From a UX perspective, it might be confusing if the user name has characters filtered from it on the back-end without letting the user know. I think better behaviour would be to validate the username on the server (probably in passport.js?) and return a 'failed to register' type error to the user if the username/email doesn't match a pattern like `[a-zA-Z0-9_-\.]+@[a-zA-Z0-9_-\.]+`.

**Comment by ian-james** [comment]
Yes, we should try and restrict the user form inputting these into the UI text box at all.
2nd best option would be to indicate immediately invalid characters.
3rd quick check on server side if valid otherwise flash message invalid name info.

**Comment by keeferrourke** [comment]
Best way of dealing with this (I think) is to use some standard email regex. [This npm module](https://github.com/chriso/validator.js) looks like a good candidate for validating many types of strings throughout the application.

**Comment by ian-james** [comment]
Yeah, that looks good. Go for it.

**Comment by keeferrourke** [comment]
Should have this issue taken care of tonight, applying validation to every input string in the IFS.
