### ISSUE TITLE
Survey Selection page

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#96]
Students can select to do a survey.
 Potentially Options as well.

**Comment by keeferrourke** [comment]
I have yet to ever get surveys working on my machine, so I'm offloading this to you @ian-james :stuck_out_tongue_winking_eye:

**Comment by ian-james** [comment]
Adding two new surveys questions and a page for student to select to do a survey.

**Comment by ian-james** [comment]
From empty Survey tables, you don't need to delete all tables.
login with an account

Go to Routes:
/createSurvey will make the surveys table
/ips will generate survey preferences for currently logged in account. It would exist if you've signed up after setting up createSurvey route.

**Comment by ian-james** [comment]
I've added OSE and SCEQ surveys to dynamic table.
I've also created /survey route to allow the student to specify when they enter a survey.
