### ISSUE TITLE
Separate Opt-In and course sign-up page

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#97]
Opt-In needs to have description of the research. Agreement toggle and continue button only.

Course selection on a 2nd page after agreement.

**Comment by keeferrourke** [comment]
TODO on this issue:

- [ ] separate the /setup route into /opt-in and /classes
- [ ] update references to /setup as /classes
- [ ] add research description, information about data collection to the consent form at /opt-in

**Comment by ian-james** [comment]
Research Descript ( consent form ) and course selection page have been separated
