### ISSUE TITLE
Add other classes to enroll and have default class.

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#98]

**Comment by keeferrourke** [comment]
Related to #77?

**Comment by keeferrourke** [comment]
Partially mitigated by commit 59f691999cf4109ab4cc05eea271eb56272c01ab, wherein users are redirected to /setup on login until a boolean 'completedSetup' in the user_registration table is set.

The code in this commit could be extended to prevent usage of the rest of the site until at least on class is selected to be enrolled. This should probably not be done until the 'account-verification' branch is merged into 'master' however.

**Comment by ian-james** [comment]
Closing this because I think we now have enough 'guards' about not being in a class that it no longer crashes.

We don't care to force them into a class just have to make sure any information retrieved isn't relient on them being in a class.
