### ISSUE TITLE
OLM/OSSM

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#99]

**Comment by keeferrourke** [comment]
?

**Comment by keeferrourke** [comment]
A quick search yields [this paper](http://d-scholarship.pitt.edu/28980/1/olm_motivation.pdf). Is that what you are referring to? What needs to be done in the IFS re: this issue?

**Comment by ian-james** [comment]
Didn't see this until now. This essentially just data visualisation of the class performances. 
The more informance we can provide about how an individual student is progress the better. They will be able to compare their progress to aggregate data form other students.
OLM - the logged in student
OSSM - The entire class

**Comment by ian-james** [comment]
Visualization and dashboard pretty much cover this. I think this is completed unless we get more information from IFS meeting about more metrics worth tracking and showing students.
